### ISSUE TITLE
"E:/Projects/multex/multex-annots/repo" not found

### ISSUE THREAD

**Issue by HirahKong** [AlexShafir/MultipleExtends#1]
repositories {
    jcenter()
    mavenCentral()
    maven { url uri('E:/Projects/multex/multex-annots/repo') }
}

Can you upload this plugin to github?

**Comment by HirahKong** [comment]
sorry,I saw it..

**Comment by AlexShafir** [comment]
Hi Hirah,

First, note that I did not make it work in the end.

Second, Lately I came to conclusion that task is doable without Annotation Processing/Bytecode Weaving. 

For example, you can subclass Fragment, create subscription flow inside it so that others could subscribe to it.

Then you can create separate fragments that can, for instance, check Google Play services presence. Main fragment re-calls its own callbacks like onViewCreated, OnDestroy etc. on supplied fragment.
